### PR TITLE
Add some generic labels

### LINKED ISSUE #2: Define list of common labels to be applied to all add-on repositories
Here is my list, but please suggest more:

 - hangout agenda
 - review
 - ..

### PR DESCRIPTION
**Pull request by mvorisek**
fix https://github.com/atk4/infrastructure/issues/2

@romaninsh add labels you want and merge + autoclose the #2 issue

### CODE REVIEW

**Comment by mvorisek** [comment]
@romaninsh legit? Can you also setup the permissions so I can add labels/reviewers to this repo?

`hasPR` label is very helpfull for issues with PR like:
image

**Comment by romaninsh** [comment]
@mvorisek thanks for this. I agree about "hasPR". 

I'll need to be careful about this PR because we can potentially loose label attachments to the issues, but I'll get it merged at some point.

**Comment by mvorisek** [comment]
> I'll get it merged at some point.

did we hit that point right now?

**Review by romaninsh — APPROVED** [review]

**Comment by mvorisek** [comment]
@romaninsh it seems it does not work - see https://github.com/atk4/ui/labels?page=1&sort=count-desc - there is no "waiting for author" label

PS we want that label in the neq/unified format across repos anyway ;-)
image

**Pull request merged**
